version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    env_file:
      - ./backend/.env

  collector:
    build: ./data_collector
    env_file:
      - ./data_collector/.env